name: GitArtwork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Artwork
        uses: jasineri/gitartwork@v1
